spring:
  application:
    name: gym-api
  datasource:
    url: "jdbc:mysql://localhost:3306/gym-api?createDatabaseIfNotExist=true"
    username: root
    password: "oS51UwnH7p8q"
  jpa:
    hibernate:
      ddl-auto: update
jwt:
  secret: "a1f3a93d2e5ee54ef6335d4bee01cb85"