spring:
  application:
    name: gym-api
  datasource:
    url: "jdbc:sqlite:gym-api.db"
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: "org.hibernate.community.dialect.SQLiteDialect"
jwt:
  secret: "a1f3a93d2e5ee54ef6335d4bee01cb85m"
